/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TeamBuilder.java
 *
 * Created on Apr 4, 2009, 3:53:56 PM
 */

package shoddybattleclient;

import java.awt.Dimension;
import java.util.ArrayList;

import shoddybattleclient.shoddybattle.*;
import shoddybattleclient.shoddybattle.Pokemon.Gender;
import shoddybattleclient.utils.*;

/**
 *
 * @author ben
 */
public class TeamBuilder extends javax.swing.JFrame {

    private TeamBuilderForm[] m_forms = new TeamBuilderForm[6];
    private ArrayList<PokemonSpecies> m_species;
    private ArrayList<PokemonMove> m_moves;

    /** Creates new form TeamBuilder */
    public TeamBuilder() {
        initComponents();
        
        MoveListParser mlp = new MoveListParser();
        m_moves = mlp.parseDocument("resources/moves2.xml");
        SpeciesListParser parser = new SpeciesListParser();
        m_species = parser.parseDocument("resources/species.xml");
        String[] species = getSpeciesList();

        //TODO: Catherine claims that she wants other numbers of teams
        for (int i = 0; i < 6; i++) {
            TeamBuilderForm tbf = new TeamBuilderForm(this, species, i);
            m_forms[i] = tbf;
            tabForms.addTab("Bulbasaur", tbf);
        }
        Dimension d = m_forms[0].getPreferredSize();
        setSize((int)d.getWidth() + 50, (int)d.getHeight() + 100);
    }

    public PokemonSpecies getSpecies(int i) {
        return m_species.get(i);
    }

    public String[] getSpeciesList() {
        String[] ret = new String[m_species.size()];
        int i = 0;
        for (PokemonSpecies ps : m_species) {
            ret[i++] = ps.getName();
        }
        return ret;
    }

    public void updateTitle(int index, String title) {
        tabForms.setTitleAt(index, title);
    }

    public ArrayList<PokemonMove> getMoveList() {
        return m_moves;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabForms = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuLoad = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuExport = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRandomise = new javax.swing.JMenuItem();
        menuBox = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Shoddy Battle - Team Builder");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("File");

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNew.setText("New Team");
        jMenu1.add(menuNew);

        menuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuLoad.setText("Load Team");
        menuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadActionPerformed(evt);
            }
        });
        jMenu1.add(menuLoad);
        jMenu1.add(jSeparator1);

        menuExport.setText("Export to Text");
        jMenu1.add(menuExport);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        menuRandomise.setText("Move to Front");
        jMenu2.add(menuRandomise);

        menuBox.setText("Randomise Team");
        jMenu2.add(menuBox);

        jMenuItem6.setText("Open Box");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabForms, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabForms, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void menuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadActionPerformed
        Pokemon p = new Pokemon(0, "Bulby", false, Gender.GENDER_MALE, 100, 1, 1, 1,
                new int[] {1,2,3,4}, new int[] {0,1,2,3}, new int[] {0,1,2,3,4,5},
                new int[] {0,10,20,30,40,50});
        m_forms[0].setPokemon(p, true);
}//GEN-LAST:event_menuLoadActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuBox;
    private javax.swing.JMenuItem menuExport;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuRandomise;
    private javax.swing.JTabbedPane tabForms;
    // End of variables declaration//GEN-END:variables

}
